#!/usr/bin/env python3
"""Vendor the canonical lib/ into both skills and guard against drift.

Usage:
    py -3 sync_lib.py            # copy lib/ into both skills
    py -3 sync_lib.py --check    # exit 1 if any vendored copy diverged from canonical

Edit ONLY the canonical copy at tools/notebooklm-common/lib/. The vendored copies
in each skill are regenerated by this script so both stay byte-identical.
"""
from __future__ import annotations

import hashlib
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CANONICAL_LIB = HERE / "lib"
SKILLS = [
    Path.home() / ".claude" / "skills" / "notebooklm-extractor",
    Path.home() / ".claude" / "skills" / "notebooklm-experto-deepresearch",
]


def _hash_dir(d: Path) -> str:
    h = hashlib.sha256()
    for f in sorted(d.rglob("*.py")):
        rel = f.relative_to(d).as_posix()
        h.update(rel.encode())
        h.update(b"\0")
        h.update(f.read_bytes())
    return h.hexdigest()


def _copy(canonical: Path, dest_skill: Path) -> Path:
    target = dest_skill / "lib"
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(canonical, target)
    return target


def main() -> int:
    check_only = "--check" in sys.argv
    if not CANONICAL_LIB.exists():
        print(f"[FAIL] canonical lib not found: {CANONICAL_LIB}")
        return 2

    canonical_hash = _hash_dir(CANONICAL_LIB)
    found_any = False

    for skill in SKILLS:
        if not skill.exists():
            print(f"[SKIP] skill not installed: {skill.name}")
            continue
        found_any = True
        if check_only:
            vendored = skill / "lib"
            if not vendored.exists():
                print(f"[FAIL] {skill.name}: no vendored lib/ (run sync_lib.py first)")
                return 1
            if _hash_dir(vendored) != canonical_hash:
                print(f"[FAIL] {skill.name}: vendored lib/ drifted from canonical")
                return 1
            print(f"[OK] {skill.name}: lib/ matches canonical")
        else:
            target = _copy(CANONICAL_LIB, skill)
            print(f"[OK] vendored lib/ -> {target}")

    if not found_any:
        print("[WARN] no target skills found — nothing to sync.")
        return 0

    if check_only:
        print("[OK] all vendored copies match the canonical lib/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
